[tool.poetry]
name = "lesfid"
version = "0.1.0"
description = ""
authors = ["alex paden <padenalex0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
farcaster = "^0.7.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
